#' Simulated monthly Kuroshio large-meander indicator
#'
#' A simulated monthly time series indicating whether the Kuroshio path is in
#' the large-meander A-type state. The dataset is provided as a univariate
#' \code{ts} object and is intended for use as an example exogenous variable
#' with \code{sst_sim}.
#'
#' @format
#' A univariate \code{ts} object with:
#' \describe{
#'   \item{frequency}{12 (monthly data)}
#'   \item{start}{January 1998}
#'   \item{end}{February 2023}
#'   \item{kuroshio_a}{Simulated binary indicator of the Kuroshio A-type path}
#' }
#'
#' @details
#' Values are encoded as 0 or 1, where 1 represents the Kuroshio A-type path
#' and 0 represents other path types. The original source information used in
#' Baba et al. (2024) was based on Kuroshio path-type records compiled by the
#' Tokyo-area mackerel fishery and oceanographic condition review group. Those
#' records distinguish A-type and non-A-type Kuroshio paths at submonthly
#' resolution. This simulated dataset has been aggregated and represented as
#' monthly data with \code{frequency = 12} for use with the package examples.
#'
#' This dataset is not the original observed Kuroshio path record. It was
#' generated by simulation based on the state-space model analysis of sea
#' temperature time series off Jogashima reported by Baba et al. (2024). The
#' name \code{kuroshio_a_sim} is used to make the simulated nature of the
#' dataset explicit. Missing values, if any, are encoded as \code{NA}.
#'
#' @source
#' Simulated data generated for \pkg{tempssm} based on Baba et al. (2024).
#' The original study's supplementary code and test data are available at:
#' \url{https://github.com/logics-of-blue/sea-temperature-trend-jogashima}
#'
#' @references
#' Baba, S., Ishii, H., and Yoshiyama, T. (2024). Estimating sea temperature
#' trends using a linear Gaussian state-space model in Jogashima, Kanagawa,
#' Japan (in Japanese with an English abstract).
#'
#' Baba, S. (2024). Supplementary code and test data for estimating sea
#' temperature trends using a linear Gaussian state-space model.
#' \url{https://github.com/logics-of-blue/sea-temperature-trend-jogashima}
#'
#' @examples
#' data(kuroshio_a_sim)
#' head(kuroshio_a_sim)
#'
"kuroshio_a_sim"
